name: Build Dashboard

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'out'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Dashboard'
          output:
            format: html
            filename: 'out/dashboard.html'
          sections:
          - title: 'Open Issues by Type'
            description: 'Queries of issues by type, using their label.'
            widgets:
            - type: 'number'
              title: 'Docs'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:documentation'
              color: 'red'
            - type: 'number'
              title: 'Feature'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:feature'
              color: 'green'
            - type: 'number'
              title: 'Up for Grabs'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:"up for grabs"'
              color: 'blue'
            - type: 'number'
              title: 'Easy Fix'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:"easy fix"'
              color: 'blue'

          
        token: ${{ github.token }}

    - name: Publish Documentation
      run: |
        git add .
        git config user.name 'Dashboard User'
        git config user.email 'nobody@nowhere'
        git commit -m 'Documentation update' --allow-empty
        git push origin gh-pages
      working-directory: out
